config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  
        has_many :microposts, dependent: :destroy
    
        before_save { email.downcase! }
        validates :name, presence: true, length: {maximum: 50}
        
        VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

        validates :email, presence: true, length: {maximum: 255},
                  uniqueness: { case_sensitive: false }
        
        has_secure_password
          validates :password, length: { minimum: 6 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session] [:email].downcase)
    if user && user.authenticate(params[:session] [:password])
      login_url user
      redirect_to user
    else
    render 'new'
    end
  end
  
  
  def destroy
    log_out 
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  
  def new
    @user = User.new
  end
  
  
  def show 
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end
  
  
  def create 
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to EventBright"
      redirect_to @user
    else render 'new'
    end 
  end 
  
  private 
  
  def user_params
    params.require(:user).permit(:name, :email, :password, 
                                  :password_confirmation)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def log_in (user)
        session[:user_id] = user.id 
    end 
    
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
 end
 
 
 def logged_in?
     !current_user.nil?
 end 
 
 
 def log_out 
     session.delete(:user_id)
     @current_user = nil
 end
end 

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<p> EventBright created by Merlin</p>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
    <div class="container">
      <%= link_to "EventBright", root_path , id: "logo" %>
       <div class="topnav"></div>
        <nav>
          <ul>
            <li><%= link_to "Home", root_path, class: "nav" %></li>
            <li><%= link_to "Help", help_path, class: "nav" %></li>
            <li><%= link_to "Log In", login_path , class: "nav" %></li>
            <li><%= link_to "Log Out", logout_path, class: "nav", method: "delete" %></li>
         </ul>
        </nav>
       </div>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif]-->
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | EventBright</title>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <% render 'layouts/shim' %>
      <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
  </head>
  <body>
    
    <%= render 'layouts/header' %> 
    <%= yield %>
    <%= render 'layouts/footer' %> 
  </body>
</html>
      

app/views/microposts/_micropost.html.erb
<li id="micropost"-<%= micropost.id %>">
<%= link_to gravatar_for(micropost.user, size:50), micropost.user %> 
<span class="user"><%= link_to micropost.user.name, micropost.user %><\span>
<span class="content"><%= micropost.content %><\span>
<span class="timestamp">
posted <% time_ago_in_words(micropost.created_at) %> ago.
<\span>
</li>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
    <head>
        <title><% yield(:title) %></title>    
    </head>
    <body>
        <h1>ABOUT</h1>
        <p>This is the about page </p>
    </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<!DOCTYPE html>
<html>
    <head>
        <title><% yield(:title) %></title>    
    </head>
    <body>
        <h1>Contact</h1>
        <p>This is the contact page </p>
    </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
    <head>
        <title><% yield(:title) %></title>    
    </head>
    <body>
        <h1>Help</h1>
        <p>This is the help pahe </p>
    </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
    <head>
        <title><% yield(:title) %></title>    
    </head>
    <body>
        <div class="homecontainer">
        <h1 class="homeheader">Welcome to EventBright</h1>
        <h3>This is the home page for the event bright application</h3>
        <%= link_to "Sign up now!", signup_path, class: "signupbuttons" %>
        </div>
    </body>
</html>
        

app/views/users/new.html.erb
<% provide(:title, "Signup") %>
<!DOCTYPE html>
<html>
    <head>
        <title><% yield(:title) %></title>    
    </head>
    <body>
      <h1>Sign Up </h1>
      <p>This is a sign up page for new users </p>
          
          
          
          <%= form_for(@user) do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name %>
          
          <%= f.label :email %>
          <%= f.email_field :email %>
          
          <%= f.label :password %>
          <%= f.password_field :password %>
          
          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation %>
          
          <%= f.submit "Create my account" %>
          <% end %>
         
          
    </body>
</html>

app/views/users/show.html.erb
<% if @user.microposts.any? %>
<h3> Microposts (<%= @user.microposts.count %> </h3>
<ol class="microposts">
<%= render @microposts %>
</ol>
<%= will_paginate @microposts %>
<% end %> 